#! /bin/bash
#This screip installs Hi Client Manager on linux ubuntu
# unzip to /opt/$APPNAME/
# copy all configs from config folder to /etc/opt/$APPNAME
# make symblink of scripts to /usr/local/bin
# make symblink of services to /etc/systemd/system/
# enable services
# start services
# delete temp

APPNAME="PiperServer"

not_empty_read(){
local DESCRIPTION=$1
local DEFAULT_VALUE=$2
local result
while [ -z $result ]; do
	read -p $DESCRIPTION -e -i $DEFAULT_VALUE result
done
echo $result
}

installConfig(){
	echo -e "Insert PiperServer and DatabseServer information \n"
	echo -e "If PiperServer is installed on the same server as HiClientManager installed leave this empty \n"
	read -p "Enter TLS Cert File address :" tls_cert_file
	echo -e "If PiperServer is installed on the same server as HiClientManager installed leave this empty \n"
	read -p "Enter TLS Private Key File address :" tls_private_key_file
	echo -e "The port that database server must listen to. default is 5050 \n"
	database_server_port=$(not_empty_read "Enter database server port :" "5050")
	echo -e "If PiperServer is behind another Server app like caddy this should be localhost othervise it can be 0.0.0.0\n"
	piper_server_address=$(not_empty_read "Enter PiperServer listening address :" "localhost")
	echo -e "The port that PiperServer must listen to. default is 5051 \n"
	piper_server_port=$(not_empty_read "Enter PiperServer listening port :" "5051")
	
	sed -i -e 's/"tlsCertFile": ".*"/"tlsCertFile": "'$tls_cert_file'"/' /etc/opt/$APPNAME/server.config
	sed -i -e 's/"tlsPrivateKetFile": ".*"/"tlsPrivateKetFile": "'$tls_private_key_file'"/' /etc/opt/$APPNAME/server.config
	sed -i -e 's/"databaseServerPort": ".*"/"databaseServerPort": "'$database_server_port'"/' /etc/opt/$APPNAME/server.config
	sed -i -e 's/"piperServerAddress": ".*"/"piperServerAddress": "'$piper_server_address'"/' /etc/opt/$APPNAME/server.config
	sed -i -e 's/"piperServerPort": ".*"/"piperServerPort": "'$piper_server_port'"/' /etc/opt/$APPNAME/server.config
	
	# creat private and publick key
	if [[ $(ls /bin/java) ]]; then
		/bin/java -jar /opt/$APPNAME/bin/PiperServer.jar -c /etc/opt/$APPNAME/auth
		echo "private and public key generated and saved in /etc/opt/$APPNAME/auth"
		if [[ $(ls /opt/HiClientManager) ]]; then
			read -e -p "HiClientManager is installed. Do you want to copy privateKey file to its auth folder ?(yes/no)" -i "yes" yes_or_no
			if [[ "$yes_or_no" == "yes" ]]; then
				cp /etc/opt/$APPNAME/auth/privateKey.pv /etc/opt/HiClientManager/auth
			fi
		fi
	else
		echo "Java virtual machine not installed first install it then run this command : java -jar /opt/$APPNAME/bin/PiperServer.jar -c /etc/opt/$APPNAME/auth"
	fi
}


wget -O /tmp/$APPNAME.zip https://s3.goolha.tk/download/PiperServer.zip
unzip /tmp/$APPNAME.zip -d /opt/$APPNAME 1> /dev/null
rm /tmp/$APPNAME.zip

mkdir /etc/opt/$APPNAME
mkdir /etc/opt/$APPNAME/auth

cp -a /opt/$APPNAME/config/. /etc/opt/$APPNAME

groupadd hitunnel 2> /dev/null
ln -s /opt/$APPNAME/services/piper-server.service /etc/systemd/system/piper-server.service

chmod +x /opt/$APPNAME/scripts/$APPNAME.sh
ln -s /opt/$APPNAME/scripts/$APPNAME.sh /usr/local/bin/$APPNAME

installConfig

systemctl enable piper-server.service
systemctl start piper-server.service




